### ISSUE TITLE
AttributeError: 'MixupDataset' object has no attribute 'mixup_to_cutmix'

### ISSUE THREAD

**Issue by crazy-winds** [seefun/TorchUtils#4]
我在使用 tu.dataset.MixupDataset 这个类时报错： AttributeError: 'MixupDataset' object has no attribute 'mixup_to_cutmix'。然后我看了一下源码，发现 MixupDataset 这里面没有 self.mixup_to_cutmix 这个属性， 而是只在参数上有 mixup_to_cutmix。
我想问一下作者，这是我使用的方法不对还是您的失误

**Comment by seefun** [comment]
抱歉，是我的失误。TorchUtils代码库最近仍在重构中，是一点个人tricks的总结，目前还并不是一个稳定的库，也没添加测试代码，所以仍然会有些bug。感谢提出！ 也欢迎提交issue和pr，我会尽快测试和解决！

**Comment by seefun** [comment]
目前看来 应该只是漏了一句
self.mixup_to_cutmix = mixup_to_cutmix

**Comment by crazy-winds** [comment]
对，我目前也只观察到这一点




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "seefun/TorchUtils"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月13日(星期天) 晚上9:48
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [seefun/TorchUtils] AttributeError: 'MixupDataset' object has no attribute 'mixup_to_cutmix' (#4)





 
目前看来 应该只是漏了一句
 self.mixup_to_cutmix = mixup_to_cutmix
