### ISSUE TITLE
Some questions of new hand

### ISSUE THREAD

**Issue by snow-tyan** [seefun/TorchUtils#8]
1. About mixup
注意到有Mixup和MixupDataset
二者是二选一即可吗
```python
mixup_func = tu.Mixup(......)
for batch, (imgs, labels) in enum(train_loader):
    imgs, labels = imgs.to(device), labels.to(device)
    imgs, labels = mixup_func(imgs, labels)
```
```python
train_dataset = tu.MixupDataset(train_dataset, ......)
```

2. About example
树叶分类的example里data transform里没加resize，也没有randomcrop centercrop是故意的吗，不需要控制input_size吗？

**Comment by seefun** [comment]
1. Mixup和MixupDataset二选一即可, Mixup是对batch图像直接mixup操作的函数，MixupDataset则是对Dataset类的包装；可参考树叶用例使用;
2. 数据的特殊性，树叶分类的example的数据，所有图像大小都是固定的224x224.

**Comment by snow-tyan** [comment]
@seefun 感谢回复，还有一个小问题关于模型融合
如果使用3个模型，每个模型都用了5折交叉，就得到15个权重。以您的经验来说，怎样对这15个权重进行融合比较好呢。
先对5折交叉取均值，得到单模的均值，再对3个模型取均值吗

**Comment by seefun** [comment]
> @seefun 感谢回复，还有一个小问题关于模型融合
> 如果使用3个模型，每个模型都用了5折交叉，就得到15个权重。以您的经验来说，怎样对这15个权重进行融合比较好呢。
> 先对5折交叉取均值，得到单模的均值，再对3个模型取均值吗

取均值的先后顺序没有区别，都和直接均值融合15个模型等价
